### ISSUE TITLE
When i put on the carved pumpkin it looks like this

### ISSUE THREAD

**Issue by Scuber2007** [ThePotatoKing55/2D-block-texture-pack#2]
![image](https://user-images.githubusercontent.com/80646955/111082299-83daff00-84d5-11eb-8bb5-a38f9df55bcc.png)

**Comment by ThePotatoKing55** [comment]
Haha, that's hilarious. I'm not quite sure how to fix this though. The head model is the same as the item.

**Comment by RubenVerg** [comment]
However, you can move where it gets placed, right? I'd suggest to move the 2D sprite in front of the face, like if it was a cardboard mask

- RubenVerg ❤️


________________________________

**Comment by ThePotatoKing55** [comment]
That's an excellent idea! I'll add that in later today.

**Comment by ThePotatoKing55** [comment]
Added!
