### ISSUE TITLE
Suggestion: Relicense under a Creative Commons license

### ISSUE THREAD

**Issue by Thanos1716** [ThePotatoKing55/2D-block-texture-pack#4]
Was just thinking, the MIT license doesn't cover artwork very well, and is more targeted towards software, so would you consider changing it to something that is more artwork focused? The one that matches up most with the MIT license is CC0 from a quick look, however CC0 is known to basically fall back to CC-BY in Europe, so that could also be an option to avoid confusion? You can find the full list of CC licenses [here](https://creativecommons.org/about/cclicenses/), this is just a suggestion, no pressure :)

**Comment by ThePotatoKing55** [comment]
I didn't realize the MIT license doesn't cover artwork well, thank you! I'll change it to CC-BY.
