### ISSUE TITLE
 Using a resource pack in my mod

### ISSUE THREAD

**Issue by LopyMine** [ThePotatoKing55/2D-block-texture-pack#6]
Hello! I wanted to know if I can take a couple of textures from your resource pack for my mod? My mod allows you to create cells for some items in the inventory and I want to take some of your textures, I can also leave a link to your resource pack and that the textures for blocks and other things were taken from you!

https://imgur.com/a/wDravXo - here is my problem...

**Comment by Thanos1716** [comment]
The license permits it, as long as you give credit.
Curious what your mod does?

**Comment by LopyMine** [comment]
So far, it is in development, it will quickly allow you to create cells for items in your inventory, just like in an enchantment table

**Comment by Thanos1716** [comment]
Cool, might have to try it out!
Tried to do the same sorta thing as a resourcepack actually.
Also if you were hoping for the full block item set, you could try my [fork](https://github.com/Thanos1716/2d-block-item-resourcepack/releases) of this pack, which is up to date with 1.20, hope you find what you need :)

**Comment by LopyMine** [comment]
Fine!

**Comment by LopyMine** [comment]
Hmm, I wanted to recolor some of the textures to look like my items, but now it's hard to figure out which block it is...
https://imgur.com/a/xfYeItB

**Comment by Thanos1716** [comment]
I feel like that would be a problem for blocks in general, since they all share the same shape, do you need to distinguish them well?

**Comment by LopyMine** [comment]
Yep, I am considering different solutions to this problem
